apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nszh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nszh
    app.kubernetes.io/part-of: dcimport
  name: dc-metro-map-nszh
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-nszh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-nszh
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:655b127d14db89ad1bae054a00e0fbbc1eb93a1dac987cedf0bb93ab255a7327
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
