apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-nszh
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/user-workload@sha256:655b127d14db89ad1bae054a00e0fbbc1eb93a1dac987cedf0bb93ab255a7327
        name: container-image
        resources: {}
status: {}
